/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as CelebrateRouteImport } from './routes/celebrate'
import { Route as IndexRouteImport } from './routes/index'

const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrateRoute = CelebrateRouteImport.update({
  id: '/celebrate',
  path: '/celebrate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/celebrate': typeof CelebrateRoute
  '/thankyou': typeof ThankyouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/celebrate': typeof CelebrateRoute
  '/thankyou': typeof ThankyouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/celebrate': typeof CelebrateRoute
  '/thankyou': typeof ThankyouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/celebrate' | '/thankyou'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/celebrate' | '/thankyou'
  id: '__root__' | '/' | '/celebrate' | '/thankyou'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelebrateRoute: typeof CelebrateRoute
  ThankyouRoute: typeof ThankyouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrate': {
      id: '/celebrate'
      path: '/celebrate'
      fullPath: '/celebrate'
      preLoaderRoute: typeof CelebrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelebrateRoute: CelebrateRoute,
  ThankyouRoute: ThankyouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
